name: acceso mv ssh

on: 
    push:

jobs:
    prueba-ssh-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: clonar repo
              uses: actions/checkout@v6
             
            - name: acceso shh
              run: |
                  ssh{{SECRETS.USER_NAME_MV}}@{{SECRETS.USER_IP_MV}}
                  pwd


