name: acceso mv ssh

on: 
    push:
        branches: [ main ]

jobs:
    prueba-ssh-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: acceso shh
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.USER_IP_MV }}
                username: ${{ secrets.USER_NAME_MV }}
                password: ${{ secrets.PASSWORD }}
                port: 22
                script: |
                  hostname -I
                  cd /home/beatr
                  mkdir GH_PRUEBA_CARPETA



