name: hola primer workflow

on:
    push:

jobs:
    prueba-primer-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: hola echo
              run: echo "primer workflow"
            
            - name: dar permisos y ejecutamos
              run: pwd



